name: Laravel CI/CD

on:
  push:
    branches: [ "uat" ] # Deploy only on UAT branch
  pull_request:
    branches: [ "uat" ] # Run tests on PRs to UAT

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: posn1
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@2
      with:
        php-version: '8.0'
        extensions: mbstring, bcmath, ctype, json, tokenizer, xml, pdo_mysql
        coverage: none

    - name: Copy .env file
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-progress --no-interaction --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Migrate Database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: posn1
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: posn1
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test

  deploy-uat:
    if: github.ref == 'refs/heads/uat' # Deploy only on UAT branch
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to UAT Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.UAT_SERVER_HOST }}
        username: ${{ secrets.UAT_SERVER_USER }}
        key: ${{ secrets.UAT_SERVER_SSH_KEY }}
        script: |
          cd /var/www/your-app
          git pull origin uat
          composer install --no-dev --no-interaction --prefer-dist
          php artisan migrate --force
          php artisan config:cache
          php artisan queue:restart
          php artisan optimize:clear
          sudo service php8.0-fpm restart
